### ISSUE TITLE
MySQL error when self hosting

### ISSUE THREAD

**Issue by Akurosia** [mattantonelli/ffxiv-triple-triad#1]
I tried to selfhost your repo.
I started the program with "bundle exec rackup" and after accessing the site via localhost:9292 i am greeted with following error message (see attached image file).
Did i missed some steps (could you maybe provide a small guide?)
Kind regards
![chrome_flgxopl4v8](https://user-images.githubusercontent.com/7465469/50016763-69e6a500-ffca-11e8-8bfd-ed24ccd219d3.png)

**Comment by mattantonelli** [comment]
This project is still a WIP, so I haven't created a proper README for it yet. This is probably something I will do after I finish the base features and do a beta launch, which I'm shooting to do sometime next week.

In the meantime, here is a rough guide for setting up the application:

1. Create a MySQL database called `triad_development` (this is set in the `database.yml`) as well as a user for this database.
2. Create a new application in [XIVAPI](https://www.xivapi.com/app). This is where we pull the data from.
3. Update your Rails Credentials with your credentials to match the example below:
```
$ rails credentials:edit
```

```yml
mysql:
  development:
    username: myuser
    password: password
xivapi_key: abc123
```
4. Run the various rake tasks
```
$ rake all:load card_sources:set card_packs:create
```

If you run into any issues, please let me know. It will help when I create the proper installation guide later.

**Comment by Akurosia** [comment]
Thanks for your quick reply.
I tried to execute "rails credentials:edit" but i am greeted with the default help page 

> Usage:
  rails new APP_PATH [options]

i also just tried to execute the other command and got following result:

> rake all:load card_sources:set card_packs:create
Traceback (most recent call last):
        1: from /usr/local/bin/rake:23:in `<main>'
/usr/local/bin/rake:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake (LoadError)

Also does the db get accessed at localhost:3306 ?

**Comment by mattantonelli** [comment]
Here's a few more steps for you. First we create the binaries (since they are not in the repo.)

```
$ bundle exec rake app:update:bin
```

Then we add one more command to the credentials setup I gave you earlier to avoid a weird Rails bug.

```
$ rm config/credentials.yml.enc
$ rails credentials:edit
```

And finally we add a `bundle exec` to the rake command for good measure. My environment prefixes this automatically so sometimes I forget to include it.

```
$ bundle exec rake all:load card_sources:set card_packs:create
```

And yes, it should be using the default MySQL port 3306.

**Comment by Akurosia** [comment]
ok so another problem :)
first of: i had to manually install/update rake as otherwise i got error messages

second: when i run "rails credentials:edit" an error is thrown.
a work around for this (sugessted by the error is to use 

> EDITOR="mate --wait" bin/rails credentials:edit

but i have to modify it to: 

> EDITOR="nano" bin/rails credentials:edit

when i do this a already prefilled file with a "secret_key_base:" is displayed where i enter with applied username, password and xivapi-key (i use the same spaces as you posted above)
> mysql:
  development:
    username: myuser
    password: password
xivapi_key: abc123

now when i run "rake all:load card_sources:set card_packs:create"
following error is displayed (i also verified that my db can be accessed with other programms)

> Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
/var/lib/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/var/lib/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_handling.rb:90:in `connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/model_schema.rb:466:in `load_schema!'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/attributes.rb:234:in `load_schema!'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/model_schema.rb:459:in `block in load_schema'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/model_schema.rb:456:in `load_schema'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/model_schema.rb:346:in `attribute_types'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/attribute_methods.rb:230:in `has_attribute?'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/relation/calculations.rb:245:in `aggregate_column'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/relation/calculations.rb:268:in `execute_simple_calculation'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/relation/calculations.rb:238:in `perform_calculation'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/relation/calculations.rb:145:in `calculate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/relation/calculations.rb:52:in `count'
/var/lib/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/querying.rb:15:in `count'
/var/www/ffxiv/ffxiv-triple-triad/lib/tasks/card_types.rake:5:in `block (2 levels) in <main>'
/var/www/ffxiv/ffxiv-triple-triad/lib/tasks/all.rake:5:in `block (2 levels) in <main>'
/var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => card_types:create
(See full trace by running task with --trace)

**Comment by mattantonelli** [comment]
I'm curious about the steps you took to "manually install/update rake".

As far as the editor is concerned for the credentials, it looks like you had to override the default to use an editor you actually have installed. You should be able to add the following line to your shell configuration file to avoid having to override this in the future:

```
export EDITOR=nano
```

As far as your MySQL error is concerned, it looks like it isn't a credentials issue (yet) but rather a connection issue. I'm going to take a guess that you're just missing the `mysql2` gem and I failed to include an obvious step in the installation:

```
$ bundle install
```

If you've already run `bundle install` then I'd like to validate that you have the gem installed with

```
$ bundle show mysql2
```

**Comment by mattantonelli** [comment]
Once we get connected to the database, you'll also need to create the necessary tables before you are able to run those rake tasks.

```
$ bundle exec rake db:schema:load
```

**Comment by Akurosia** [comment]
so in the beginning (even before writein the issue here) i already ran `bundle install`
what i did now was `gem install rake && gem update rake` as manual instalation of rake

the output for `bundle show mysql2` is `/var/lib/gems/2.5.0/gems/mysql2-0.5.2`

and i still get the MYSQL exception

**Comment by mattantonelli** [comment]
I know you confirmed you can access the DB with other programs, but can you make sure it can be accessed through the following:

```
$ mysql -u myuser -p -D triad_development
```

**Comment by Akurosia** [comment]
tried it and i can see the mysql shell

**Comment by mattantonelli** [comment]
Can you confirm the location for the socket file of your MySQL installation? The `config/database.yml` is looking for it in `/var/lib/mysql/mysql.sock` but if yours is located elsewhere then this will need to be updated.

I'm going to guess that the following command returns an error for you.
```
$ ls /var/lib/mysql/mysql.sock
```

**Comment by Akurosia** [comment]
ok so yes you were right :)
my sock file is located here: `/var/run/mysqld/mysqld.sock`

after adjusting the database.yml i ran
`bundle exec rake db:schema:load`
`rake all:load card_sources:set card_packs:create`

now its running fine and no errors are displayed :)

**Comment by mattantonelli** [comment]
Fantastic! Thanks for walking through this with me. It will help a lot when I'm writing the README.

**Comment by Akurosia** [comment]
Short update when i tried to update: i had again the issue with rake and this time it was fixed after running `bundle update rake` (just to keep all the information together)
