### ISSUE TITLE
Owned cards not showing on the 'packs' page

### ISSUE THREAD

**Issue by Myrhial** [mattantonelli/ffxiv-triple-triad#5]
I remember in the past when I used the website, and can also see references to this in the code, that the 'packs' page would show which cards in a pack you already own, which is a really great feature. 

However, I'm currently no longer able to see this on the page, despite being logged in and having filled in my collection. I have tried logging in again and visiting the site from another machine. It is working on the 'my cards' page, where cards I own are greyed out. But on the 'packs' page, this isn't happening for any entries, despite for example owning every card from the Bronze Triad Card pack.

**Comment by mattantonelli** [comment]
Thanks for pointing out the references in the code. I had completely forgotten I added this!

**Comment by mattantonelli** [comment]
![image](https://user-images.githubusercontent.com/1176304/59683087-7af4b680-91a5-11e9-8595-2a034058d169.png)
