### ISSUE TITLE
The button "select your cards" is misplaced (?) 

### ISSUE THREAD

**Issue by eZ0** [mattantonelli/ffxiv-triple-triad#7]
Hi,

Thank you for making such a wonderful tool!

I use Safari 14.1.2 on macOs BigSur (11.5.1) and I see that instead of being in a flex class the form is positioned outside of it. I'd suggest the form and the button are either on the same line, or they aligned left (flex-start)

How it is now:

<img width="1245" alt="Screenshot 2021-08-02 at 10 33 08" src="https://user-images.githubusercontent.com/1408613/127829969-454260ae-bee7-48f6-8715-01ce52dbbeeb.png">

How I think it's supposed to be

<img width="1196" alt="Screenshot 2021-08-02 at 10 32 43" src="https://user-images.githubusercontent.com/1408613/127830011-a6ea663f-169b-4746-b2ae-45cb71454c2d.png">

If you need help with styling - let me know!

**Comment by mattantonelli** [comment]
This was changed last night to accomodate for the addition of the Number input field. Previously I managed to get the suggested style working with some Bootstrap column ordering, but the newly widened form no longer fit within the old size threshold.

I tried to get the original styling work with pure flex, but it falls apart when the browser is <1200px wide. I'm not sure that the original styling is going to be possible with a pure flex solution.

**Comment by mattantonelli** [comment]
@eZ0 I gave this another go this morning. It's a bit janky but it's back to how it used to look. Let me know what you think.

**Comment by eZ0** [comment]
@mattantonelli it's perfect, ty for your work!

**Comment by eZ0** [comment]
If you want to use pure flex, I would suggest to use the flex-wrap: wrap, so that anything that's not fitting on now line would flow to another. Or you can just let the button stay on one line, under the form and align everything at flex-start 

Another option would be that select your cards button would be an icon-button (=less space) and you show on mouse over the alt text; also making number input field smaller (shorter) will win some space

**Comment by mattantonelli** [comment]
It's stylistically important that the "Select Your Cards" and "Hide Owned" buttons are anchored to the edge of the table. I don't believe you can anchor elements like that if you allow the contents to wrap.

**Comment by eZ0** [comment]
if that's the requirement - no, you can't do that
