### ISSUE TITLE
Select Cards page doesn't split for Page 12

### ISSUE THREAD

**Issue by AriannaStory** [mattantonelli/ffxiv-triple-triad#9]
In the app, the "Select Cards" feature [only shows 11 pages](https://user-images.githubusercontent.com/4652603/136717080-6a54cef5-3904-4652-8404-18535eccd15f.png), whereas the game client [shows 12 pages](https://user-images.githubusercontent.com/4652603/136717194-c7d1a9d7-d386-434d-95db-f3c34852ea03.png). 

I've only given it a cursory look, but it seems like it has to do with cards arrays being [sliced here](https://github.com/mattantonelli/ffxiv-triple-triad/blob/75b63ef7417f2441cda12c228a1817c8457ae196/app/assets/javascripts/cards-select.coffee#L22-L24), which is something I'd be happy to submit a PR for, but I wanted to check in before starting work, partially because I'm not entirely sure about the "hide missing cards" bit's purpose.

Thanks!

**Comment by mattantonelli** [comment]
This was introduced when SE separated the "Ex" cards from the rest of the list.

Fixing this will probably require adding a separate class to Ex cards (currently those with `order_group == 5`) and ensuring they begin on their own page after the rest of the list. The logic for `page_max` and `navigate_to` will need to be updated to accomodate this. It's probably not going to be pretty. :)

**Comment by mattantonelli** [comment]
Resolved by 0871350
